### ISSUE TITLE
 Exception when accessing metadata on some LSF nodes

### ISSUE THREAD

**Issue by jgriss** [spectra-cluster/spectra-cluster-2#73]
The application exists on some LSF nodes with the following exception (after clustering is complete):
```
  21:28:04.463 [main] DEBUG org.spectra.cluster.engine.GreedyClusteringEngine - Merging clusters with threshold 0.050
  21:28:04.532 [main] DEBUG org.spectra.cluster.tools.SpectraClusterTool - Clustering completed in 234 seconds
  Error: Could not open table 111

Command error:
  java.lang.RuntimeException: Could not open table 111
        at org.iq80.leveldb.impl.TableCache.getTable(TableCache.java:98)
        at org.iq80.leveldb.impl.TableCache.newIterator(TableCache.java:79)
        at org.iq80.leveldb.impl.TableCache.newIterator(TableCache.java:74)
        at org.iq80.leveldb.impl.Level.get(Level.java:131)
        at org.iq80.leveldb.impl.Version.get(Version.java:172)
        at org.iq80.leveldb.impl.VersionSet.get(VersionSet.java:223)
        at org.iq80.leveldb.impl.DbImpl.get(DbImpl.java:616)
        at org.iq80.leveldb.impl.DbImpl.get(DbImpl.java:577)
        at org.spectra.cluster.io.properties.MapDBPropertyStorage.getProperty(MapDBPropertyStorage.java:107)
        at org.spectra.cluster.io.cluster.DotClusteringWriter.addSpectrum(DotClusteringWriter.java:129)
        at org.spectra.cluster.io.cluster.DotClusteringWriter.appendClusters(DotClusteringWriter.java:72)
        at org.spectra.cluster.tools.SpectraClusterTool.run(SpectraClusterTool.java:186)
        at org.spectra.cluster.tools.SpectraClusterTool.main(SpectraClusterTool.java:58)
  Caused by: java.io.FileNotFoundException: /tmp/properties-35843591121042247502022697267727551/000111.sst (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at org.iq80.leveldb.impl.TableCache$TableAndFile.<init>(TableCache.java:123)
        at org.iq80.leveldb.impl.TableCache$TableAndFile.<init>(TableCache.java:114)
        at org.iq80.leveldb.impl.TableCache$1.load(TableCache.java:67)
        at org.iq80.leveldb.impl.TableCache$1.load(TableCache.java:62)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
        at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
        at org.iq80.leveldb.impl.TableCache.getTable(TableCache.java:91)
        ... 12 more
```

**Comment by jgriss** [comment]
This is LSF specific and has to be fixed in the pipeline

**Comment by ypriverol** [comment]
This has been fixed in the current tool because we use now a configurable path
